---
title: "Descriptions of Instruments Scored by PROscorer"
author: "Ray Baser"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    toc: true
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{Descriptions of Instruments Scored by PROscorer}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction:

This vignette includes descriptions of the instruments scored by the
[PROscorer](https://cran.r-project.org/package=PROscorer) package.  

__PROBLEM:__ Patient reported outcome (PRO) measures and other PRO-like
instruments are often poorly and inadequately described in formal research
protocol documents and in published reports of study results.

__CONSEQUENCES:__ In protocols, this makes it difficult or impossible to
evaluate the suitability of the PRO measures as study outcomes, including
whether the proposed analysis plans are appropriate.   The same consequences
apply to published study results.  In addition, poor PRO measure descriptions in
published studies hinder the ability interpret, replicate, and reproduce study
results.  Altogether, this impedes the scientific progress of research that
relies upon PRO and similar measures.

__SOLUTION:__ Create a repository of high-quality descriptions of specific PRO
instruments (i.e., this vignette document), written according to explicit
guidelines for describing PRO measures in research protocols and papers.

This document is intended to ease the burden of writing research protocols and
manuscripts for studies with quality of life (QOL) or other patient-reported
outcome (PRO) measures as endpoints.

The descriptions are written with sufficient detail to be included in formal 
research protocol documents that utilize the instruments as outcome measures. 
They are also suitable for the "Measures" subsection of manuscripts reporting 
the results of such studies (potentially with editing, to meet word limits). 
They were written with these purposes in mind, and follow the below _"Guidelines
for Describing PRO Measures"_ that I developed based on several sources of "best
practices" for describing PRO measures (references coming soon) and on my 
personal experience as a protocol review committee chair at a large cancer
center.  


# How to Use These Descriptions:

Each instrument description is complete with relevant references.  In most
cases, the description can be copied and pasted directly into your document with
only very minor modifications.

The following modifications are needed:  

*  Move the references to the References section of the your document, and
update in-text citation numbers accordingly.

*  If not all of the scored scales of the instrument are of interest to the
study objectives, then add a sentence indicating the focal scale scores.

Please cite the PROscorer package and this vignette document (I hope to obtain
DOIs soon):

  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
  (PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.
  https://cran.r-project.org/package=PROscorer
  
  Baser, RE (2023). Descriptions of Instruments Scored by PROscorer. R Package
  Vignette version 0.0.4. https://cran.r-project.org/package=PROscorer


# Guidelines for Describing Patient Reported Outcome Measures (PROMs):

I developed the following guidelines during my years of service as a chair of 
the Biostatistics Protocol Review Committee at a large cancer treatment and 
research institution.  If you would like to contribute a scoring function to the 
PROscorer package, please use these guidelines to write a description of your 
instrument.  I plan to update these guidelines soon into a more user-friendly
checklist, but this should get you started.

Information to Include in Descriptions of PRO Measures:

1.  The total number of questions/items on the instrument(s), their response
format (e.g., 5-point Likert scale, True/False, etc.), and the time period for
which respondents are asked to consider each item (e.g., “In past week, how
often … ”).

2.	The names of any subscale scores that the instrument yields, descriptions of
the specific constructs that each of these subscales are intended to measure,
the number of items included on each subscale, the range of scores that is
possible on each subscale, the interpretation of higher scores (e.g., higher
scores indicate more/less severe symptom levels), and, if available, reliability
coefficients (e.g., internal consistency, test-retest) for each subscale score
and, if relevant, for the instrument’s total score.

    a.  Many PROM scores have validated cut-points that divide the scores into 2
    or more range categories believed to be clinically or diagnostically
    relevant.  If the PROM has such score categories, provide the
    score cut-points or ranges defining each category as well as the clinical
    interpretation of each category.

3.	A citation and reference to the instrument's original psychometric validation
study, and any relevant subsequent validation studies. At least one reference
should indicate how the instrument is scored.  Please also mention the
_PROscorer_ R package and the relevant _PROscorer_ scoring function, and please
cite the _PROscorer_ R package.

4.	Estimates of how long it will take study participants to complete the PROM,
as well as an estimate of how long it will take them to complete the full
battery of PROMs.


# Instrument Descriptions: 

## Female Sexual Function Index (FSFI)
The **Female Sexual Function Index (FSFI)** is a multidimensional self-report
measure of female sexual functioning**[REF 1]**.  It asks women to rate its 19
items according to "the past 4 weeks" using a Likert-type response format.  Four
of the items are scored from 1 to 5, and fifteen are scored from 0 to 5 (with 0
corresponding to response option "Did not attempt intercourse").  It takes
approximately 5-10 minutes to complete.

In additional to the FSFI Total score, the FSFI produces 6 subscale scores
corresponding to distinct sexual function domains: Desire (2 items), Arousal (4
items), Lubrication (4 items), Orgasm (3 items), Satisfaction (3 items), and
Pain (3 items).  The FSFI scoring algorithm sums the items on each subscale and
then scales the sums so that each subscale has a maximum possible score of 6. 
The subscales have a minimum possible score of 0 except for Desire and
Satisfaction, which have minimum possible scores of 1.2 and 0.8, respectively. 
This is because those two subscales contain the four items scored 1 to 5
(instead of 0 to 5).  The FSFI total score is the sum of the 6 subscale scores
and ranges from 2 to 36.  Higher scores indicate better functioning for all
scores.  Accurate scoring for the FSFI is available in the _PROscorer_ R
package using the __`fsfi()`__ function**[REF 2]**.

The initial FSFI validation study**[REF 1]** reported excellent internal
consistency reliability for the FSFI total score (Cronbach’s α = 0.97) and
subscales (Cronbach’s α range = 0.89 to 0.96).  A FSFI total score of 26.55 or
less has been validated as a diagnostic cut off score suggestive of female
sexual dysfunction**[REF 3]**.  The FSFI has also been validated for assessing
sexual function among sexually active female cancer survivors**[REF 4]**.

#### REFERENCES:
1.  Rosen, R, Brown, C, Heiman, J, Leiblum, S, Meston, C, Shabsigh, R, …
D’Agostino, R. (2000). The Female Sexual Function Index (FSFI): a
multidimensional self-report instrument for the assessment of female sexual
function. _Journal of Sex & Marital Therapy_, 26(2), 191–208.

2.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.

3.  Wiegel, M, Meston, C, & Rosen, R. (2005). The Female Sexual Function Index
(FSFI): Cross-Validation and Development of Clinical Cutoff Scores. _Journal of
Sex & Marital Therapy_, 31(1), 1–20.

4.  Baser, RE, Li, Y, & Carter, J. (2012). Psychometric validation of the female
sexual function index (FSFI) in cancer survivors. _Cancer_, 118(18), 4606–4618.




## Cognitive Causation (CC) and Negative Affect in Risk (NAR)
The **Cognitive Causation (CC)** and **Negative Affect in Risk (NAR)** scales
are two new measures of intuitive, gut-level aspects of cancer risk
perception**[REF 1]**.  The CC scale measures the extent to which respondents
believe that thoughts about cancer risk can encourage the development of the
disease, and that minimizing such thoughts can actually reduce cancer risk.  It
originally contained 10 items**[REF 1]**, but it is recommended to score only 7
items**[REF 2]**.  The NAR scale contains 6 items and measures negative
anticipatory affect, or negative emotions (e.g., fear) generated during cancer
risk information processing.  Both the CC and NAR items have 4, Likert-type
response options that are assigned numeric scores: Strongly Disagree = 0,
Disagree = 1, Agree = 2, and Strongly Agree = 3.  Each instrument takes
approximately 2-5 minutes to complete.

The preferred scoring method is to first calculate the mean of the item scores,
and then transform that mean to range from 0 to 100.  Higher scores indicate
greater levels of the constructs being measured**[REF 2]**.  A score should only
be assigned to respondents who validly completed at least half of items on a
given scale.  The CC and NAR scales can be accurately scored using the
__`narcc()`__ function in the _PROscorer_ R package **[REF 3]**.

Both scales have had consistently high reliability across diverse samples, with
Cronbach's alpha coefficients all 0.89 or higher**[REF 1]**.  The items have
also demonstrated measurement invariance across highly diverse samples**[REF
2]**.

#### REFERENCES:
1.  Hay, JL, Baser, R, Weinstein, ND, Li, Y, Primavera, L, & Kemeny, MM. (2014).
Examining intuitive risk perceptions for cancer in diverse populations. _Health,
Risk & Society_, 16(3), 227–242.

2.  Baser, RE, Li, Y, Brennessel, D, Kemeny, MM, & Hay, JL. (2017). Measurement
Invariance of Intuitive Cancer Risk Perceptions Across Diverse Populations: The
Cognitive Causation and Negative Affect in Risk Scales. _Journal of Health
Psychology_.

3.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.




## EORTC QLQ-BLM30

The European Organization for Research and Treatment of Cancer (EORTC) QLQ-BLM30
Muscle-Invasive Bladder Cancer Module is a 30-item questionnaire designed to
assess health-related quality of life (HRQoL) in patients with muscle-invasive
bladder cancer.**[REF 1]** The questionnaire asks patients to indicate the
extent to which they have experienced each of the problems “during the past
week” on a 4-point Likert-type response scale from “Not at all” to “Very much”.

The 30 items of the QLQ-BLM30 yield 7 scale scores.  Of the 7 scores, 6 are
Symptom Scales and 1 is a Functional Scale.  Five of the Symptom Scales are
based on multiple items: Urinary Symptoms (7 items), Urostomy Problems (6
items), Future Perspective (3 items), Abdominal Bloating and Flatulence (2
items), and Body Image (3 items).  One Symptom Scale is based on a single item
(Catheter Use Problems).  The single Functional Scale, Sexual Functioning, is
based on either 2, 4, 6, or 7 items, depending on whether the respondent is male
or female and whether he or she is sexually active.  Psychometric validation
results for the QLQ-BLM30 are lacking.**[REF 1]**

The scoring procedure for the QLQ-BLM30 (available at
https://qol.eortc.org/questionnaires/) transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the functional scale
represent high/healthy levels of functioning, but high scores for the symptom
scales/items represent high levels of symptomatology/problems.  Accurate scoring
for the EORTC QLQ-BLM30 is available in the _PROscorer_ R package using the
__`qlq_blm30()`__ function**[REF 2]**.  Note that the QLQ-BLM30 instructs
respondents to answer subsets of questions conditional on whether they have a
urostomy or not, whether they used a catheter during the past week, whether they
are a man or a woman, and whether they have been sexually active during the past
4 weeks.  Therefore, not all of the scale scores are applicable to all patients.


#### REFERENCES: 

1. Rammant E, Fox L, Beyer K, et al. The current use of the EORTC QLQ-NMIBC24
and QLQ-BLM30 questionnaires for the assessment of health-related quality of
life in bladder cancer patients: a systematic review. _Qual Life Res_. Published
online January 17, 2023. \doi{10.1007/s11136-022-03335-4}

2.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.


## EORTC QLQ-C30 (version 3.0)
The European Organization for Research and Treatment of Cancer (EORTC) QLQ-C30
Quality of Life Questionnaire (version 3.0) is a 30-item questionnaire designed
to assess the quality of life of cancer patients**[REF 1]**.  The 30 items of
the QLQ-C30 yield both multi-item scale scores and single-item scores, for a
total of 16 distinct scores.  These include one Global Health Status/QoL scale
(2 items), five functional scales (Physical Functioning, 5 items; Role
Functioning, 2 items; Emotional Functioning, 4 items; Cognitive Functioning, 2
items; and Social Functioning, 2 items), three symptom scales (Fatigue, 3 items;
Nausea and Vomiting, 2 items; and Pain, 2 items), six single item symptom scores
(Dyspnea, Insomnia, Appetite Loss, Constipation, Diarrhea, and Financial
Difficulties; all from single items), and the more recently validated overall
summary score (calculated from the other scores, excluding Global Health
Status/QoL and Financial Difficulties)**[REF 2]**.  The questionnaire asks
patients to indicate the extent to which they have experienced each of the
problems “during the past week” on a 4-point Likert-type scale from “Not at all”
to “Very much”.  The 2 exceptions are the 2 items of the Global Health
Status/QoL scale, which patients are asked to rate on a 7-point scale from “Very
poor” to “Excellent”.

The scoring procedure for the QLQ-C30**[REF 3]** transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the Global Health
Status/QoL scale represents high QoL, high scores for the functional scales
represent high/healthy levels of functioning,  but high scores for the symptom
scales/items represent high levels of symptomatology/problems.  The newer
overall summary score also ranges from 0 to 100, with higher scores indicating
better functioning and lower levels of symptoms.  Accurate scoring for the EORTC
QLQ-C30 (version 3.0), including the newer overall summary score, is available
in the _PROscorer_ R package using the __`qlq_c30()`__ function**[REF 4]**.  The
QLQ-C30 has been extensively validated and is widely used in clinical trials. 
The multi-item scales generally have good internal consistency reliability
coefficients**[REF 1]**.




#### REFERENCES:
1.	Aaronson NK, Ahmedzai S, Bergman B, Bullinger M, Cull A, Duez NJ, Filiberti 
A, Flechtner H, Fleishman SB, de Haes JCJM, Kaasa S, Klee MC, Osoba D, Razavi D,
Rofe PB, Schraub S, Sneeuw KCA, Sullivan M, Takeda F (1993). The European
Organisation for Research and Treatment of Cancer QLQ-C30: A quality-of-life
instrument for use in international clinical trials in oncology.  _Journal of
the National Cancer Institute_, ; 85: 365-376.

2.  Giesinger JM, Kieffer JM, Fayers PM, Groenvold M, Petersen MA, Scott NW,
Sprangers MAG, Velikova G, Aaronson NK (2016). Replication and validation of
higher order models demonstrated that a summary score for the EORTC QLQ-C30 is
robust. _Journal of Clinical Epidemiology 69_:79–88.

3.	Fayers PM, Aaronson NK, Bjordal K, Groenvold M, Curran D, Bottomley A, on
behalf of the EORTC Quality of Life Group.  _The EORTC QLQ-C30 Scoring Manual
(3rd Edition)_.  Published by: European Organisation for Research and Treatment
of Cancer, Brussels 2001.

4.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.




## EORTC QLQ-CR38

The European Organization for Research and Treatment of Cancer (EORTC) QLQ-CR38
Colorectal Cancer Module is a 38-item questionnaire designed to
assess health-related quality of life (HRQoL) in patients with colorectal 
cancer.**[REF 1]** The questionnaire asks patients to indicate the
extent to which they have experienced each of the problems “during the past
week” on a 4-point Likert-type response scale from “Not at all” to “Very much”.

The 38 items of the QLQ-CR38 yield 12 scale scores.  Of the 12 scores, 8 are
Symptom Scales and 4 are Functional Scales.  Seven of the Symptom Scales are
based on multiple items: Micturition Problems (3 items), Gastrointestinal Tract
Symptoms (5 items), Chemotherapy Side-Effects (3 items), Problems with
Defecation (Only for Pts WITHOUT a stoma) (7 items), Stoma-Related Problems
(Only for Pts w/stoma) (7 items), Male Sexual Problems (2 items), and Female
Sexual Problems (2 items).  There is 1 single-item symptom scale (Weight Loss).
Two of the Functional Scales are based on multiple items: Body Image (3 items),
and Sexual Functioning (2 items).  The other 2 Functional Scales are based on
single items (Sexual Enjoyment and Future Perspective).

Note that the QLQ-CR38 instructs respondents to answer subsets of questions
conditional on whether they have a have a stoma or not, whether they are a man
or a woman, and whether they have been sexually active during the past 4 weeks.
Therefore, not all of the scale scores are applicable to all patients.  

The scoring procedure for the QLQ-CR38 transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the functional scale
represent high/healthy levels of functioning, but high scores for the symptom
scales/items represent high levels of symptomatology/problems.  Accurate scoring
for the EORTC QLQ-CR38 is available in the _PROscorer_ R package using the
__`qlq_cr38()`__ function**[REF 2]**. The scoring instructions for the QLQ-CR38
are no longer available on the EORTC website, and the QLQ-CR38 seems to have
been superseded by the QLQ-CR29**[REF 3]**, which was designed in response to
concerns that the QLQ-CR38 was outdated and no longer adequately assessed the
side effects and possible functional advantages of current treatment regiments
for colorectal cancer.

#### REFERENCES: 

1. Sprangers MAG, te Velde A, Aaronson NK. The construction and testing of the
EORTC colorectal cancer-specific quality of life questionnaire module
(QLQ-CR38). _European Journal of Cancer_. 1999;35(2):238-247.
\doi{10.1016/S0959-8049(98)00357-8}

2.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.

3. Gujral S, Conroy T, Fleissner C, et al. Assessing quality of life in patients
with colorectal cancer: An update of the EORTC quality of life questionnaire.
European Journal of Cancer. 2007;43(10):1564-1573.
\doi{10.1016/j.ejca.2007.04.005}



## EORTC QLQ-CX24

The European Organization for Research and Treatment of Cancer (EORTC) QLQ-CX24
Cervical Cancer Module is a 24-item questionnaire designed to assess
health-related quality of life (HRQoL) in patients with cervical cancer.**[REF 1]**  
The questionnaire asks patients to indicate the extent to which they have
experienced each of the problems “during the past week” on a 4-point Likert-type
response scale from “Not at all” to “Very much”.

The 24 items of the QLQ-CX24 yield both multi-item scale scores and single-item
scores, for a total of 9 distinct scores.  Of the 9 scores, 7 are Symptom Scales
and 2 are Functional Scales.  Three of the Symptom Scales are based on multiple
items: Symptom Experience (11 items), Body Image (3 items), and
Sexual/Vaginal Functioning (4 items).  The other 4 Symptom Scales
(Lymphoedema, Peripheral Neuropathy, Menopausal Symptoms, and Sexual Worry) and
both Functional Scales (Sexual Activity, Sexual Enjoyment) are all based on
single items. In the original psychometric validation study of the QLQ-CX24,
internal consistency reliability coefficients for the multi-item scales were
0.72 for Symptom Experience, 0.86 for Body Image, and 0.87 for Sexual/Vaginal
Functioning.**[REF 1]**

The scoring procedure for the QLQ-CX24 (available at
https://qol.eortc.org/questionnaires/) transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the functional
scales represent high/healthy levels of functioning, but high scores for the
symptom scales/items represent high levels of symptomatology/problems.  Accurate
scoring for the EORTC QLQ-CX24 is available in the _PROscorer_ R package using
the __`qlq_cx24()`__ function**[REF 2]**.  Note that the QLQ-CX24 instructs
respondents to answer the last 5 questions on the instrument __only__ if they
have been sexually active during the past 4 weeks.  These 5 items include all 4
items on the Sexual/Vaginal Functioning symptom scale and the 1 item on the
Sexual Enjoyment functional scale.  These scale scores will be missing for
respondents who were not sexually active during the 4 weeks before completing
the questionnaire.



#### REFERENCES: 

1. Greimel ER, Kuljanic Vlasic K, Waldenstrom AC, et al. The European
Organization for Research and Treatment of Cancer (EORTC) Quality-of-Life
questionnaire cervical cancer module. _Cancer_. 2006;107(8):1812-1822.
\doi{10.1002/cncr.22217}

2.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.



## EORTC QLQ-LMC21

The European Organization for Research and Treatment of Cancer (EORTC) QLQ-LMC21
Colorectal Liver Cancer Module is a 21-item questionnaire designed to assess
health-related quality of life (HRQoL) in patients with colorectal liver
metastases.**[REF 1, REF 2]** The questionnaire asks patients to indicate the
extent to which they have experienced each of the problems “during the past
week” on a 4-point Likert-type response scale from “Not at all” to “Very much”.

The 21 items of the QLQ-LMC21 yield both multi-item scale scores and single-item
scores, for a total of 13 distinct scores.  Of these, all 13 are Symptom Scales.
Four of the Symptom Scales are based on multiple items: Nutritional problems (2
items), Fatigue (3 items), Pain (3 items), and Emotional problems (4 items). The
other 9 Symptom Scales (Weight loss, Taste, Dry mouth, Sore mouth/tongue,
Peripheral neuropathy, Jaundice, Contact with friends, Talking about feelings,
and Sex life) are all based on single items. In the original psychometric
validation study of the QLQ-LMC21, internal consistency reliability coefficients
for the multi-item scales ranged from 0.69-0.87 for Nutrition problems,
0.89-0.93 for Fatigue, 0.73-0.78 for Pain, and 0.78-0.82 for Emotional
problems.**[REF 2]**

The scoring procedure for the QLQ-LMC21 (available at
https://qol.eortc.org/questionnaires/) transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the
symptom scales/items represent high levels of symptomatology/problems.  
Scoring for the EORTC QLQ-LMC21 is available in the _PROscorer_ R package using
the __`qlq_lmc21()`__ function**[REF 3]**.  



#### REFERENCES: 

1. Kavadas V, Blazeby JM, et al.  Development of an EORTC disease-specific
quality of life questionnaire for use in patients with liver metastases from
colorectal cancer. \emph{Eur J Cancer}. 2003 Jun;39(9):1259-63.  

2. Blazeby JM, Fayers P, Conroy T, et al. Validation of the EORTC QLQ-LCM21
Questionnaire for Assessment of Patient-Reported Outcomes During Treatment of
Colorectal Liver Metastases. \emph{Br J Surg 96}:291-298, 2009.  

3. Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.  





## EORTC QLQ-PAN26
The European Organization for Research and Treatment of Cancer (EORTC) QLQ-PAN26
Pancreatic Cancer Module is a 26-item questionnaire designed to assess 
health-related quality of life (HRQoL) in patients with pancreatic cancer.
**[REF 1]**  The questionnaire asks patients to indicate the extent to which they have
experienced each of the problems “during the past week” on a 4-point Likert-type
response scale from “Not at all” to “Very much”.  The 26 items of the QLQ-PAN26
yield both multi-item scale scores and single-item scores, for a total of 17
distinct scores.  These include two multi-item functional scales (Satisfaction
with Health Care, 2 items; Sexuality, 2 items), five multi-item symptom scales
(Pancreatic Pain, 4 items; Digestive Symptoms, 2 items; Hepatic Symptoms, 2
items; Altered Bowel Habit, 2 items; Body Image, 2 items;), and 10 single item
symptom scales (Bloating, Taste, Indigestion, Flatulence, Weight Loss, Weakness
in Arms and Legs, Dry Mouth, Troubled with Side-Effects, Future Worries, and
Planning of Activities).**[REF 1]**.  In a large psychometric validation study
of the QLQ-PAN26, internal consistency reliability coefficients for the
multi-item scales were generally above 0.70 at the pre-surgical baseline
assessment as well as at 14- and 60-day post-surgical assessments, with the
exception of the Hepatic Symptoms scale which had poor post-surgery
reliability.**[REF 2]**

The scoring procedure for the QLQ-PAN26 (available at
https://qol.eortc.org/questionnaires/) transforms all of the scale and
single-item scores to range from 0 to 100.  High scores for the functional
scales represent high/healthy levels of functioning, but high scores for the
symptom scales/items represent high levels of symptomatology/problems.  Accurate
scoring for the EORTC QLQ-PAN26 is available in the _PROscorer_ R package using
the __`qlq_pan26()`__ function**[REF 3]**.  

NOTE: At the time this scoring function was written (April 2022), the QLQ-PAN26
had completed Phase 3 testing; however, the official scoring instructions from
the EORTC warned that this scaling structure is still preliminary and may change
in the future (see https://qol.eortc.org/questionnaires/).


#### REFERENCES:
1.	Fitzsimmons D, Johnson CD, George S, et al. Development of a disease specific
quality of life (QoL) questionnaire module to supplement the EORTC core
cancer QoL questionnaire, the QLQ-PAN26 in patients with pancreatic cancer.
_Eur. J. Cancer 35_: 939-941, 1999.

2. Eaton A, Karanicolas PJ, MChir CDJ, Bottomley A, Allen PJ, Gonen M.
Psychometric Validation of the EORTC QLQ-PAN26 Pancreatic Cancer Module for
Assessing Health Related Quality of Life after Pancreatic Resection. Journal of
the Pancreas. Published online January 1, 2017. Accessed May 10, 2023.
https://www.scinapse.io/papers/2592882746

3.  Baser, RE (2023). PROscorer: Scoring Functions for Patient-Reported Outcome
(PRO) Measures and Other Psychometric Instruments. R Package Version 0.0.4.


